version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Task.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - Server=localhost;Database=TaskDb;Trusted_Connection=True;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
