version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: PayrollManagement.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PayrollDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
